language: ruby
cache: bundler
sudo: false

script: bundle exec ruby test/test_execjs.rb

matrix:
  include:
    - rvm: 2.0.0
      env: EXECJS_RUNTIME=Node
    - rvm: 2.0.0
      env: EXECJS_RUNTIME=RubyRacer

    - rvm: 2.1
      env: EXECJS_RUNTIME=Node
    - rvm: 2.1
      env: EXECJS_RUNTIME=RubyRacer

    - rvm: 2.2
      env: EXECJS_RUNTIME=Node
    - rvm: 2.2
      env: EXECJS_RUNTIME=RubyRacer

    - rvm: jruby-19mode
      env: EXECJS_RUNTIME=Node
    - rvm: jruby-19mode
      env: EXECJS_RUNTIME=RubyRhino

    - os: osx
      rvm: 2.2
      env: EXECJS_RUNTIME=Node
